---
name: full-calendar
---
DateField:
  default_config:
    showcalendar: true

---
Name: mimevalidator-ics
Only:
  moduleexists: mimevalidator
---
File:
  allowed_extensions:
   - ics
Injector:
  Upload_Validator:
    class: MimeUploadValidator
HTTP:
  MimeTypes:
    ics: 'text/plain'
